version: '3.4'

services:
  samba:
    image: ghcr.io/ahayden/filebox:base
    container_name: samba
    hostname: samba
    extra_hosts:
      - "samba:127.0.0.1"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./smb.conf:/etc/samba/smb.conf:ro
      - samba-var-lib-samba:/var/lib/samba
      - samba-etc:/etc
      - /mnt/share:/mnt/share:z

networks:
  default:

volumes:
  samba-var-lib-samba:
  samba-etc:
